In [1]:
import pandas as pd
import numpy as np

In [2]:
movies=pd.read_csv(r'C:\Users\D\Desktop\movies\tmdb_5000_movies.csv')
credits=pd.read_csv(r'C:\Users\D\Desktop\movies\tmdb_5000_credits.csv')

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
movies=movies.merge(credits,on='title')

In [6]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [7]:
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [8]:
#filter data
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.6+ KB

In [9]:
#checking data is missing or not
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [10]:
movies.dropna(inplace=True)

In [11]:
# checking duplicate data
movies.duplicated().sum()

0

In [12]:
import ast

In [13]:
def convert(obj):
    l=[]
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [14]:
movies['genres']=movies['genres'].apply(convert)

In [15]:
movies['keywords']=movies['keywords'].apply(convert)

In [16]:
#filter cast function
def convert3(obj):
    l=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter !=3:
            l.append(i['name'])
            counter+=1
        else:
            break
        l.append(i['name'])
    return l

In [17]:
movies['cast']=movies['cast'].apply(convert3)

In [18]:
#filtering crew 
def fetch_director(obj):
    l=[]
    for i in ast.literal_eval(obj):
        if i['job']== 'Director':
            l.append(i['name'])
            break
    return l

In [19]:
movies['crew']=movies['crew'].apply(fetch_director)

In [20]:
#converting to list
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [21]:
#removing space
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [22]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [23]:
new_df=movies[['movie_id','title','tags']]

In [24]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [25]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\D\AppData\Local\Temp\ipykernel_9824\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [26]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington SamWorthington ZoeSaldana ZoeSaldana SigourneyWeaver SigourneyWeaver JamesCameron'

In [27]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\D\AppData\Local\Temp\ipykernel_9824\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [28]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington samworthington zoesaldana zoesaldana sigourneyweaver sigourneyweaver jamescameron'

In [29]:
new_df['tags'][1]

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnnydepp johnnydepp orlandobloom orlandobloom keiraknightley keiraknightley goreverbinski"

In [30]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [31]:
# creating a function 
def stem(text):
    y=[]
    
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [32]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\D\AppData\Local\Temp\ipykernel_9824\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [33]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [34]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [35]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [36]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [37]:
cv.get_feature_names()

C:\ProgramData\Anaconda\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2009',
 '20th',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 'aaron',
 'aaroneckhart',
 'aarontaylor',
 'abandon',
 'abbiecornish',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'adam',
 'adambrodi',
 'adamgarcia',
 'adamsandl',
 'adamscott',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'akshaykumar',
 'al',
 'alabama',
 'alan',
 'alanarkin',
 'alanrickman',
 'alaska',
 'albert',
 'albertbrook',
 'albertfinney',
 'alcohol',
 'alecbaldwin',
 'alecguin',
 'alex',
 'alexanderskarsgård',
 'alexandradaddario',
 'alexapenavega',
 'alexisbledel',
 'alexkendrick',
 'alexpettyf',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alicebraga',
 'aliciasilverston',
 'aliciawitt',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'alilart',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alzheimer',
 'amanda',
 'amandabyn',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'ambassador',
 'amberheard',
 'ambertamblyn',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'americaferrera',
 'american',
 'americanabroad',
 'americanfootbal',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amypoehl',
 'amysmart',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'andrewgarfield',
 'android',
 'andy',
 'andygarcía',
 'andysamberg',
 'andyserki',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annabellasciorra',
 'annafari',
 'annafriel',
 'annakendrick',
 'annasophiarobb',
 'anne',
 'annebancroft',
 'annehathaway',
 'annehech',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anthropomorph',
 'anti',
 'antihero',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'arab',
 'arch',
 'archaeologist',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armandassant',
 'armi',
 'armiehamm',
 'arminmueller',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'asabutterfield',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashleytisdal',
 'ashtonkutch',
 'asia',
 'asid',
 'ask',
 'aspir',
 'assassin',
 'assault',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'athlet',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'audreytaut',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awaken',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'bailey',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrypepp',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'bear',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'benchaplin',
 'bend',
 'beneath',
 'benedictcumberbatch',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'berniemac',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'big',
 'bigger',
 'biggest',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmoseley',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billyconnolli',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blade',
 'blakel',
 'blame',
 'blend',
 'blind',
 'bliss',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobgunton',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'bonniehunt',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'braddourif',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brand',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breath',
 'breckinmey',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brentonthwait',
 'brentspin',
 'brettratn',
 'brian',
 'briancox',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'bridgetfonda',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'britmarl',
 'brittanymurphi',
 'brittrobertson',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucecampbel',
 'brucedern',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryancranston',
 'bryansing',
 'brycedallashoward',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'burtlancast',
 'burtreynold',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'buy',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'cameronbright',
 'camerondiaz',
 'camgigandet',
 'camillabel',
 'camp',
 'campaign',
 'campbell',
 'campbellscott',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candid',
 'canin',
 'cannib',
 'capabl',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'carriefish',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherinemccormack',
 'catherineo',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cedrictheentertain',
 'celebr',
 'cellphon',
 'cemeteri',
 'center',
 'central',
 'centuri',
 'centuries',
 'century',
 'certain',
 'chadmichaelmurray',
 'chain',
 'chainsaw',
 'challeng',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charless',
 'charli',
 'charlie',
 'charlieday',
 'charliehunnam',
 'charliesheen',
 'charlizetheron',
 'charlotterampl',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'children',
 'chill',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloëgracemoretz',
 'chloësevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chriso',
 'chrispin',
 'chrispratt',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christoph',
 'christopherguest',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherreev',
 'christopherwalken',
 'christophwaltz',
 'christuck',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciaránhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clarkgabl',
 'clash',
 'class',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'cleaduval',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colehaus',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commit',
 'common',
 'commun',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'condit',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connel',
 'connienielsen',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'contest',
 'continu',
 'contract',
 'control',
 'controversi',
 'convent',
 'convers',
 'convict',
 'convinc',
 'cook',
 'cool',
 'cooper',
 'cop',
 ...]

In [38]:
from sklearn.metrics.pairwise import cosine_similarity

In [39]:
similarity=cosine_similarity(vectors)

In [40]:
similarity

array([[1.        , 0.06825236, 0.07271792, ..., 0.04170288, 0.        ,
        0.        ],
       [0.06825236, 1.        , 0.05073463, ..., 0.02182179, 0.        ,
        0.02204334],
       [0.07271792, 0.05073463, 1.        , ..., 0.02324953, 0.        ,
        0.        ],
       ...,
       [0.04170288, 0.02182179, 0.02324953, ..., 1.        , 0.04082483,
        0.0404061 ],
       [0.        , 0.        , 0.        , ..., 0.04082483, 1.        ,
        0.08247861],
       [0.        , 0.02204334, 0.        , ..., 0.0404061 , 0.08247861,
        1.        ]])

In [41]:
def recommed(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distances=similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [42]:
recommed('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman
American Psycho
Harsh Times

In [43]:
recommed('Avatar')

Aliens vs Predator: Requiem
Aliens
Guardians of the Galaxy
The Book of Life
Star Trek Into Darkness